@startuml
'https://plantuml.com/class-diagram

'RBAC role based access control

class User
'class UserDetails
'class Profile
'class Account
'class Credential
class Role
class UserRole
class Permission
class RolePermission

User o-- Role
UserRole o-- User
UserRole o-- Role

'class UserPermission

@enduml